name: Deploy to Develop
on:
  push:
    branches:
      - develop

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.json secret-dev.json.gpg
        env: 
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_APP_LOGTIME_API_DEV }}'
          channelId: live
          projectId: app-logtime-api-dev